//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTarea4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public string ID_Usuario { get; set; }
        public string Nombre { get; set; }
        public string Apeliido { get; set; }
        public string Password { get; set; }
    }
}
